### PR TITLE
jump to task fixed partially, selective reloading in place

### LINKED ISSUE #184: Profile app to find cause of lag after entering command

### LINKED ISSUE #188: Make jump to task work

### PR DESCRIPTION
**Pull request by KnytJC**
Jumping to task only works if the task list is being displayed already. So it will not work only when the user firstly uses alias-related commands and then add or edit a task. I can't figure out why if the left panel reloads the jump to task feature doesn't work. 

Selective reloading in place now.

close #188 
close #184

### CODE REVIEW

File: src/main/java/seedu/address/ui/UiManager.java [hunk 1]
```diff
@@ -122,13 +122,17 @@ private void handleJumpToListRequestEvent(JumpToListRequestEvent event) {
     private void handleDisplayTaskListEvent(DisplayTaskListEvent event) {
         logger.info(LogsCenter.getEventHandlingLogMessage(event));
 		TaskListPanel listPanel = newMainWindow.getTaskListPanel();
-		listPanel = TaskListPanel.loadTaskList(newMainWindow.primaryStage, newMainWindow.getTaskListLeftPlaceholder(), event.list);
+		if (!listPanel.getIsShowingTaskList()) {
+			listPanel = TaskListPanel.loadTaskList(newMainWindow.primaryStage, newMainWindow.getTaskListLeftPlaceholder(), event.list);
```
Comment (kabir-plod) [inline src/main/java/seedu/address/ui/UiManager.java]: Method name a little confusing. If it returns a boolean then you can remove the 'get' from it --> listPanel.isShowingTaskList()

File: src/main/java/seedu/address/ui/TaskListPanel.java [hunk 2]
```diff
@@ -26,12 +26,15 @@
     private static final String FXML = "TaskListPanel.fxml";
     private VBox panel;
     private AnchorPane placeHolderPane;
-
+    //@@author A0142184L
+    private static boolean isShowingTaskList;
+    //@@author
```
Comment (kabir-plod) [inline src/main/java/seedu/address/ui/TaskListPanel.java]: I think this shouldn't be static since the variable is linked to the instance of the panel, not the class. Correct me if I'm wrong

File: src/main/java/seedu/address/ui/UiManager.java [hunk 3]
```diff
@@ -122,13 +122,17 @@ private void handleJumpToListRequestEvent(JumpToListRequestEvent event) {
     private void handleDisplayTaskListEvent(DisplayTaskListEvent event) {
         logger.info(LogsCenter.getEventHandlingLogMessage(event));
```
Comment (kabir-plod) [inline src/main/java/seedu/address/ui/UiManager.java]: When is this method called?

Comment (KnytJC) [inline src/main/java/seedu/address/ui/UiManager.java]: this is called when display task list event is posted by the add/edit/etc commands

File: src/main/java/seedu/address/ui/UiManager.java (hunk 1 above)
Comment (KnytJC) [inline src/main/java/seedu/address/ui/UiManager.java]: corrected, thanks!

File: src/main/java/seedu/address/ui/TaskListPanel.java (hunk 2 above)
Comment (KnytJC) [inline src/main/java/seedu/address/ui/TaskListPanel.java]: hmm, i need to change this boolean inside the load method which is a static method. Actually I'm not that sure about when to use private static

File: src/main/java/seedu/address/ui/UiManager.java (hunk 3 above)
Comment (kabir-plod) [inline src/main/java/seedu/address/ui/UiManager.java]: Is the event already in the commands? I can only see it in ChangeStatusCommand

Comment (KnytJC) [inline src/main/java/seedu/address/ui/UiManager.java]: yes it is in all task related commands, except for undo and redo

**Comment by kabir-plod** [comment]
Please fix conflict and then merge into master @KnytJC
